SKIPWORDS = (
    "a",
    "ab",
    "aboard",
    "about",
    "above",
    "across",
    "after",
    "against",
    "al",
    "along",
    "amid",
    "among",
    "an",
    "and",
    "anti",
    "around",
    "as",
    "at",
    "before",
    "behind",
    "below",
    "beneath",
    "beside",
    "besides",
    "between",
    "beyond",
    "but",
    "by",
    "d",
    "da",
    "das",
    "de",
    "del",
    "dell",
    "dello",
    "dei",
    "degli",
    "della",
    "dell",
    "delle",
    "dem",
    "den",
    "der",
    "des",
    "despite",
    "die",
    "do",
    "down",
    "du",
    "during",
    "ein",
    "eine",
    "einem",
    "einen",
    "einer",
    "eines",
    "el",
    "en",
    "et",
    "except",
    "for",
    "from",
    "gli",
    "i",
    "il",
    "in",
    "inside",
    "into",
    "is",
    "l",
    "la",
    "las",
    "le",
    "les",
    "like",
    "lo",
    "los",
    "near",
    "nor",
    "of",
    "off",
    "on",
    "onto",
    "or",
    "over",
    "past",
    "per",
    "plus",
    "round",
    "save",
    "since",
    "so",
    "some",
    "sur",
    "than",
    "the",
    "through",
    "to",
    "toward",
    "towards",
    "un",
    "una",
    "unas",
    "under",
    "underneath",
    "une",
    "unlike",
    "uno",
    "unos",
    "until",
    "up",
    "upon",
    "versus",
    "via",
    "von",
    "while",
    "with",
    "within",
    "without",
    "yet",
    "zu",
    "zum",
)

CROSSREF_TO_BIB = {
    "book-section": "inbook",
    "monograph": "book",
    "report-component": "techreport",
    "report": "techreport",
    "peer-review": "article",
    "book-track": "inbook",
    "journal-article": "article",
    "book-part": "inbook",
    "other": "misc",
    "book": "book",
    "journal-volume": "misc",
    "book-set": "misc",
    "reference-entry": "inbook",
    "proceedings-article": "inproceedings",
    "journal": "misc",
    "component": "misc",
    "book-chapter": "inbook",
    "proceedings-series": "misc",
    "report-series": "misc",
    "proceedings": "proceedings",
    "database": "misc",
    "standard": "misc",
    "reference-book": "book",
    "posted-content": "misc",
    "journal-issue": "misc",
    "dissertation": "phdthesis",
    "grant": "misc",
    "dataset": "misc",
    "book-series": "misc",
    "edited-book": "book",
}